
import { GoogleGenAI, Type, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;
if (!API_KEY) {
    throw new Error("API_KEY environment variable not set");
}
const ai = new GoogleGenAI({ apiKey: API_KEY });

/**
 * Generates meme captions for an image using Gemini.
 * @param imageData Base64 encoded image data.
 * @param mimeType The MIME type of the image.
 * @returns A promise that resolves to an array of 5 caption strings.
 */
export async function generateCaptions(imageData: string, mimeType: string): Promise<string[]> {
  const prompt = 'Analyze this image and generate exactly 5 short, witty, and funny meme captions that are relevant to the image content. The captions should be in the style of popular internet memes.';

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: {
        parts: [
          { inlineData: { data: imageData, mimeType: mimeType } },
          { text: prompt },
        ],
      },
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            captions: {
              type: Type.ARRAY,
              items: {
                type: Type.STRING,
                description: 'A funny meme caption.'
              },
              description: 'An array of 5 meme captions.'
            }
          },
          required: ['captions']
        }
      }
    });
    
    const jsonResponse = JSON.parse(response.text);

    if (jsonResponse && Array.isArray(jsonResponse.captions) && jsonResponse.captions.length > 0) {
      return jsonResponse.captions.slice(0, 5);
    }
    
    console.warn("AI response was not in the expected format:", jsonResponse);
    throw new Error('Failed to parse captions from AI response.');
  } catch (error) {
    console.error("Error generating captions:", error);
    throw new Error('An error occurred while communicating with the AI.');
  }
}

/**
 * Edits an image based on a text prompt using Gemini.
 * @param imageData Base64 encoded image data.
 * @param mimeType The MIME type of the image.
 * @param prompt The text prompt describing the edit.
 * @returns A promise that resolves to the base64 encoded string of the edited image.
 */
export async function editImage(imageData: string, mimeType: string, prompt: string): Promise<string> {
    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
            parts: [
                { inlineData: { data: imageData, mimeType: mimeType } },
                { text: prompt },
            ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });
        
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                return part.inlineData.data;
            }
        }

        throw new Error('No image was generated by the AI.');

    } catch (error) {
        console.error("Error editing image:", error);
        throw new Error('An error occurred while communicating with the AI for image editing.');
    }
}
